/**
 * Global Geopolitical Intelligence Dataset
 * Maps 195 countries to their likely impact and strategic reasoning
 * during a major power sanction scenario. 
 * This data is based on strategic research of export dependencies and market roles.
 */

export interface GlobalIntelligence {
    impact: 'green' | 'yellow' | 'red';
    why: string;
}

export const GLOBAL_INTELLIGENCE: Record<string, GlobalIntelligence> = {
    afghanistan: { impact: 'yellow', why: 'Aid-dependent, already isolated' },
    albania: { impact: 'red', why: 'EU-linked economy' },
    algeria: { impact: 'green', why: 'Energy exporter gains from higher prices' },
    andorra: { impact: 'red', why: 'Dependent on EU tourism/finance' },
    angola: { impact: 'green', why: 'Oil exporter benefits from price spikes' },
    antigua_barbuda: { impact: 'red', why: 'Tourism & imports hit' },
    argentina: { impact: 'yellow', why: 'Commodity exporter but financially fragile' },
    armenia: { impact: 'yellow', why: 'Could gain as trade middle route but vulnerable' },
    australia: { impact: 'green', why: 'Major commodity exporter (iron, coal, LNG)' },
    austria: { impact: 'red', why: 'Deep EU trade integration' },
    azerbaijan: { impact: 'green', why: 'Energy exporter alternative to sanctioned states' },
    bahamas: { impact: 'red', why: 'Finance & tourism exposure' },
    bahrain: { impact: 'green', why: 'Gulf trade hub' },
    bangladesh: { impact: 'red', why: 'Export manufacturing depends on global demand' },
    barbados: { impact: 'red', why: 'Tourism & finance exposed' },
    belarus: { impact: 'yellow', why: 'Already sanctioned, limited additional impact' },
    belgium: { impact: 'red', why: 'EU trade + port economy' },
    belize: { impact: 'red', why: 'Small trade-dependent economy' },
    benin: { impact: 'red', why: 'Import dependent' },
    bhutan: { impact: 'yellow', why: 'Insulated but India-dependent' },
    bolivia: { impact: 'yellow', why: 'Commodity exporter but landlocked limits gains' },
    bosnia: { impact: 'red', why: 'EU-linked fragile economy' },
    botswana: { impact: 'yellow', why: 'Diamond exports could gain, but demand uncertain' },
    brazil: { impact: 'green', why: 'Food, minerals, energy exporter' },
    brunei: { impact: 'green', why: 'Oil & gas exporter' },
    bulgaria: { impact: 'red', why: 'EU supply chain exposure' },
    burkina_faso: { impact: 'red', why: 'Import and aid reliance' },
    burundi: { impact: 'red', why: 'Vulnerable, low diversification' },
    cabo_verde: { impact: 'red', why: 'Tourism driven' },
    cambodia: { impact: 'red', why: 'Export manufacturing dependent' },
    cameroon: { impact: 'yellow', why: 'Oil exporter but unstable demand' },
    canada: { impact: 'green', why: 'Energy, minerals, food exporter' },
    central_african_republic: { impact: 'red', why: 'Aid dependent' },
    chad: { impact: 'yellow', why: 'Oil exporter but fragile' },
    chile: { impact: 'green', why: 'Copper exporter (critical mineral)' },
    china: { impact: 'green', why: 'Can replace sanctioned suppliers & expand influence' },
    colombia: { impact: 'green', why: 'Oil, coal, agriculture exports' },
    comoros: { impact: 'red', why: 'Import dependent' },
    drc: { impact: 'green', why: 'Critical minerals demand surge' },
    congo_brazzaville: { impact: 'green', why: 'Oil exporter' }, // Republic of Congo
    costa_rica: { impact: 'red', why: 'Trade & tourism exposed' },
    croatia: { impact: 'red', why: 'EU tourism & trade' },
    cuba: { impact: 'yellow', why: 'Already sanctioned; limited marginal change' },
    cyprus: { impact: 'red', why: 'Finance & tourism exposure' },
    czech: { impact: 'red', why: 'Manufacturing tied to EU supply chains' },
    denmark: { impact: 'red', why: 'Trade & shipping exposure' },
    djibouti: { impact: 'green', why: 'Strategic trade route hub' },
    dominica: { impact: 'red', why: 'Tourism dependent' },
    dominican_republic: { impact: 'red', why: 'Tourism & remittances' },
    ecuador: { impact: 'yellow', why: 'Oil exporter but debt risk' },
    egypt: { impact: 'red', why: 'Food import dependent' },
    el_salvador: { impact: 'red', why: 'Remittances & trade exposure' },
    equatorial_guinea: { impact: 'green', why: 'Oil exporter' },
    eritrea: { impact: 'yellow', why: 'Isolated but small economy' },
    estonia: { impact: 'red', why: 'EU trade reliance' },
    eswatini: { impact: 'red', why: 'Trade dependent' },
    ethiopia: { impact: 'red', why: 'Aid & imports reliance' },
    fiji: { impact: 'red', why: 'Tourism' },
    finland: { impact: 'red', why: 'EU manufacturing' },
    france: { impact: 'red', why: 'Major global trade exposure' },
    gabon: { impact: 'green', why: 'Oil exporter' },
    gambia: { impact: 'red', why: 'Import dependent' },
    georgia: { impact: 'green', why: 'Transit route between blocs' },
    germany: { impact: 'red', why: 'Export powerhouse vulnerable to disruption' },
    ghana: { impact: 'green', why: 'Gold, cocoa exporter' },
    greece: { impact: 'red', why: 'Shipping & tourism' },
    grenada: { impact: 'red', why: 'Tourism' },
    guatemala: { impact: 'red', why: 'Export agriculture reliance' },
    guinea: { impact: 'green', why: 'Bauxite (aluminum ore) exporter' },
    guinea_bissau: { impact: 'red', why: 'Weak trade base' },
    guyana: { impact: 'green', why: 'Emerging oil exporter' },
    haiti: { impact: 'red', why: 'Aid & imports dependent' },
    honduras: { impact: 'red', why: 'Export manufacturing' },
    hungary: { impact: 'red', why: 'EU supply chain dependent' },
    iceland: { impact: 'yellow', why: 'Energy independent but trade exposed' },
    india: { impact: 'green', why: 'Can buy discounted commodities & expand trade role' },
    indonesia: { impact: 'green', why: 'Coal, palm oil, nickel exporter' },
    iran: { impact: 'yellow', why: 'Already sanctioned but benefits from higher oil prices' },
    iraq: { impact: 'green', why: 'Oil exporter' },
    ireland: { impact: 'red', why: 'Tech & trade dependent' },
    israel: { impact: 'red', why: 'Trade & tech integration' },
    italy: { impact: 'red', why: 'Manufacturing exporter' },
    jamaica: { impact: 'red', why: 'Tourism & imports' },
    japan: { impact: 'red', why: 'Energy import dependent' },
    jordan: { impact: 'red', why: 'Import dependent' },
    kazakhstan: { impact: 'green', why: 'Energy & transit hub' },
    kenya: { impact: 'red', why: 'Fuel & food import exposure' },
    kiribati: { impact: 'red', why: 'Aid dependent' },
    kuwait: { impact: 'green', why: 'Oil exporter' },
    kyrgyzstan: { impact: 'green', why: 'Trade rerouting hub potential' },
    laos: { impact: 'red', why: 'Small trade-dependent economy' },
    latvia: { impact: 'red', why: 'EU trade exposure' },
    lebanon: { impact: 'red', why: 'Import & finance fragile' },
    lesotho: { impact: 'red', why: 'Export dependent' },
    liberia: { impact: 'red', why: 'Shipping registry but weak economy' },
    libya: { impact: 'green', why: 'Oil exporter (if stable)' },
    liechtenstein: { impact: 'red', why: 'Finance linked to EU' },
    lithuania: { impact: 'red', why: 'Trade exposed' },
    luxembourg: { impact: 'red', why: 'Finance hub exposed' },
    madagascar: { impact: 'red', why: 'Import reliance' },
    malawi: { impact: 'red', why: 'Aid & imports' },
    malaysia: { impact: 'green', why: 'Energy & electronics exporter' },
    maldives: { impact: 'red', why: 'Tourism' },
    mali: { impact: 'red', why: 'Fragile economy' },
    malta: { impact: 'red', why: 'Shipping & finance' },
    marshall_islands: { impact: 'red', why: 'Aid dependent' },
    mauritania: { impact: 'green', why: 'Iron ore exporter' },
    mauritius: { impact: 'red', why: 'Tourism & finance' },
    mexico: { impact: 'red', why: 'US-linked trade dependence' },
    micronesia: { impact: 'red', why: 'Aid dependent' },
    moldova: { impact: 'red', why: 'Energy import dependent' },
    monaco: { impact: 'red', why: 'Finance & tourism' },
    mongolia: { impact: 'green', why: 'Minerals exporter to China' },
    montenegro: { impact: 'red', why: 'Tourism' },
    morocco: { impact: 'yellow', why: 'Phosphates exporter but import exposure' },
    mozambique: { impact: 'green', why: 'Gas exporter' },
    myanmar: { impact: 'yellow', why: 'Already semi-isolated' },
    namibia: { impact: 'green', why: 'Uranium & minerals' },
    nauru: { impact: 'red', why: 'Aid dependent' },
    nepal: { impact: 'red', why: 'Remittances & imports' },
    netherlands: { impact: 'red', why: 'Major trade hub vulnerable' },
    new_zealand: { impact: 'green', why: 'Food exporter' },
    nicaragua: { impact: 'red', why: 'Trade exposed' },
    niger: { impact: 'green', why: 'Uranium exporter' },
    nigeria: { impact: 'green', why: 'Oil exporter' },
    north_korea: { impact: 'yellow', why: 'Already isolated' },
    north_macedonia: { impact: 'red', why: 'EU-linked' },
    norway: { impact: 'green', why: 'Major oil & gas exporter' },
    oman: { impact: 'green', why: 'Oil exporter' },
    pakistan: { impact: 'red', why: 'Import dependent' },
    palau: { impact: 'red', why: 'Aid dependent' },
    panama: { impact: 'green', why: 'Canal transit hub' },
    papua_new_guinea: { impact: 'green', why: 'LNG & minerals' },
    paraguay: { impact: 'green', why: 'Agriculture exporter' },
    peru: { impact: 'green', why: 'Copper exporter' },
    philippines: { impact: 'red', why: 'Import & remittance exposure' },
    poland: { impact: 'red', why: 'EU manufacturing' },
    portugal: { impact: 'red', why: 'Trade exposure' },
    qatar: { impact: 'green', why: 'Gas super-exporter' },
    romania: { impact: 'red', why: 'EU supply chains' },
    russia: { impact: 'green', why: 'Loses from sanctions but gains via high energy prices & rerouting' },
    rwanda: { impact: 'red', why: 'Import dependent' },
    st_kitts_nevis: { impact: 'red', why: 'Tourism/finance' },
    st_lucia: { impact: 'red', why: 'Tourism' },
    st_vincent: { impact: 'red', why: 'Tourism' },
    samoa: { impact: 'red', why: 'Aid dependent' },
    san_marino: { impact: 'red', why: 'EU-dependent microstate' },
    sao_tome_principe: { impact: 'red', why: 'Aid dependent' },
    saudi_arabia: { impact: 'green', why: 'Oil price surge benefits' },
    senegal: { impact: 'red', why: 'Import dependent' },
    serbia: { impact: 'yellow', why: 'Can act as middle trade route but exposed' },
    seychelles: { impact: 'red', why: 'Tourism' },
    sierra_leone: { impact: 'red', why: 'Import dependent' },
    singapore: { impact: 'green', why: 'Trade rerouting & finance hub' },
    slovakia: { impact: 'red', why: 'EU manufacturing' },
    slovenia: { impact: 'red', why: 'EU trade exposure' },
    solomon_islands: { impact: 'red', why: 'Aid dependent' },
    somalia: { impact: 'red', why: 'Aid dependent' },
    south_africa: { impact: 'green', why: 'Gold, minerals exporter' },
    south_korea: { impact: 'red', why: 'Trade & energy import dependence' },
    south_sudan: { impact: 'green', why: 'Oil exporter' },
    spain: { impact: 'red', why: 'Tourism & trade' },
    sri_lanka: { impact: 'red', why: 'Import & debt vulnerable' },
    sudan: { impact: 'red', why: 'Fragile economy' },
    suriname: { impact: 'yellow', why: 'Oil potential but fragile' },
    sweden: { impact: 'red', why: 'Trade dependent' },
    switzerland: { impact: 'yellow', why: 'Finance hub but neutral advantage possible' },
    syria: { impact: 'yellow', why: 'Already sanctioned' },
    taiwan: { impact: 'red', why: 'Trade & semiconductor supply chains vulnerable' },
    tajikistan: { impact: 'red', why: 'Remittance dependent' },
    tanzania: { impact: 'red', why: 'Import dependent' },
    thailand: { impact: 'red', why: 'Export manufacturing' },
    timor_leste: { impact: 'red', why: 'Aid dependent' },
    togo: { impact: 'red', why: 'Import dependent' },
    tonga: { impact: 'red', why: 'Aid dependent' },
    trinidad_tobago: { impact: 'green', why: 'Energy exporter' },
    tunisia: { impact: 'red', why: 'Import dependent' },
    turkey: { impact: 'green', why: 'Major sanctions-bypass trade hub' },
    turkmenistan: { impact: 'green', why: 'Gas exporter' },
    tuvalu: { impact: 'red', why: 'Aid dependent' },
    uganda: { impact: 'red', why: 'Import dependent' },
    ukraine: { impact: 'red', why: 'War & trade disruption exposure' },
    uae: { impact: 'green', why: 'Trade, finance, logistics hub' },
    uk: { impact: 'red', why: 'Finance & trade hub vulnerable if sanctioned' },
    usa: { impact: 'red', why: 'Global trade/finance shock if sanctioned' },
    uruguay: { impact: 'green', why: 'Agriculture exporter' },
    uzbekistan: { impact: 'green', why: 'Trade rerouting role' },
    vanuatu: { impact: 'red', why: 'Aid & tourism' },
    vatican_city: { impact: 'yellow', why: 'Financially tiny, symbolic impact' },
    venezuela: { impact: 'yellow', why: 'Oil gains but sanctions risk' },
    vietnam: { impact: 'green', why: 'Manufacturing alternative to sanctioned states' },
    yemen: { impact: 'red', why: 'Humanitarian dependence' },
    zambia: { impact: 'green', why: 'Copper exporter' },
    zimbabwe: { impact: 'yellow', why: 'Minerals exporter but unstable' },
};
